### PR TITLE
Update FastText links

### PR DESCRIPTION
**Pull request by Ayushk4**
The previous links to fasttext weren't working, so the newer ones on fasttext's website have been added here.

### CODE REVIEW

**Comment by oxinabox** [comment]
Why is CI failing?

**Comment by Ayushk4** [comment]
Something to do with GloVe embeddings. I am looking into it and will get back to you.

**Comment by oxinabox** [comment]
breaking for same reason as #24 I suspect?

**Comment by Ayushk4** [comment]
> breaking for same reason as #24 I suspect?

I don't think so. 

It's giving this error - `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` during the execution of GloVe testsets.

For 0.7 (apple's osx) it's giving error outside of test in this line - https://github.com/JuliaText/Embeddings.jl/blob/f12e909fd78dd58eb1cd980953a7af89f87d6f5d/test/runtests.jl#L83
and in this next testset "Specific" on line 89.

The tests are failing for Embeddings.jl#master - (Here's a pr sent to my own fork that changes nothing in the codebase and it's failing.) https://github.com/Ayushk4/Embeddings.jl/pull/1

**Comment by oxinabox** [comment]
I am going to merge this now and will fix any issues in #27

**Pull request merged**
