### PR TITLE
add second author, some text updates

### PR DESCRIPTION
**Pull request by dellison**
This PR adds my author info and a makes a couple changes to the text. Feel free to take the changes selectively, or make any updates you'd like! Thanks.

### CODE REVIEW

**Comment by oxinabox** [comment]
Do you have an affiliation?

**Comment by dellison** [comment]
Well, I finished my MSc earlier this summer at the University of Washington, but since I'm not a student anymore I'm not sure if that's appropriate to include. I could ask my advisor about that. (And I don't really think I want to put my employer, since this was all on my own time).

**Comment by oxinabox** [comment]
It is fine.
I have a feeling there is a bug in JOSS's system  if you don't list an affiliation, but that can be dealt with during review

**Comment by dellison** [comment]
That sounds good.

**Pull request merged**
